variables:
  PHP_ERROR_REPORTING: E_ALL
  COMPOSER_ALLOW_SUPERUSER: 1
  GIT_STRATEGY: fetch

stages:
  - tests

unit test lastest:
  image: wpdesknet/phpunit-woocommerce:0-0
  stage: tests
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunit-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  variables:
    XDEBUG_MODE: coverage
  script:
    - composer install --no-progress --no-ansi --no-interaction
    - vendor/bin/phpunit --do-not-cache-result --log-junit phpunit-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never
